# Generated by Django 4.2.7 on 2023-11-11 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='room_types', to='preference.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomTypeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='choices', to='student.batch')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='choices', to='preference.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.SmallIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='preferences', to='student.group')),
                ('room_type_choice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='preferences', to='preference.roomtypechoice')),
            ],
        ),
    ]
