# Generated by Django 4.2.7 on 2023-11-12 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='room_type_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='preferences', to='preference.roomtype'),
        ),
    ]
