# Generated by Django 4.2.7 on 2023-11-14 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_batch_is_preference_filling_live'),
        ('preference', '0002_alter_preference_room_type_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='student.group'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='room_type_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='preference.roomtype'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='preference.hostel'),
        ),
        migrations.AlterField(
            model_name='roomtypechoice',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='student.batch'),
        ),
        migrations.AlterField(
            model_name='roomtypechoice',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='preference.roomtype'),
        ),
    ]
