# Generated by Django 4.2.7 on 2023-11-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0003_alter_preference_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='caretaker_email',
            field=models.EmailField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostel',
            name='caretaker_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostel',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='is_allotment_enabled',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='room_size',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='rooms_count',
            field=models.PositiveSmallIntegerField(default=100),
            preserve_default=False,
        ),
    ]
