# Generated by Django 4.2.7 on 2023-11-14 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0004_hostel_caretaker_email_hostel_caretaker_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='room_type_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='preference.roomtypechoice'),
        ),
    ]
