# Generated by Django 4.2.7 on 2023-11-15 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_batch_is_preference_filling_live_section'),
        ('preference', '0007_alter_preference_room_type_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='is_allotment_enabled',
        ),
        migrations.RemoveField(
            model_name='roomtypechoice',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='roomtypechoice',
            name='gender',
        ),
        migrations.AddField(
            model_name='roomtypechoice',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='student.section'),
        ),
    ]
