# Generated by Django 4.2.7 on 2023-11-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_invitation_unique_together'),
        ('preference', '0008_remove_roomtype_is_allotment_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together={('room_type_choice', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='roomtype',
            unique_together={('name', 'hostel')},
        ),
        migrations.AlterUniqueTogether(
            name='roomtypechoice',
            unique_together={('room_type', 'section')},
        ),
    ]
