# Generated by Django 4.2.7 on 2023-12-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0009_alter_hostel_name_alter_preference_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
