# Generated by Django 4.2.7 on 2024-02-24 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0010_roomtype_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('room_no', models.CharField(max_length=5)),
                ('total_capacity', models.PositiveSmallIntegerField()),
                ('current_capacity', models.PositiveSmallIntegerField(default=0)),
                ('is_allotted', models.BooleanField(default=False)),
                ('is_registered', models.BooleanField(default=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='preference.hostel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='preference.roomtype')),
            ],
            options={
                'unique_together': {('room_type', 'room_no', 'level')},
            },
        ),
    ]
