# Generated by Django 4.2.7 on 2024-02-24 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0011_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='total_capacity',
        ),
    ]
