# Generated by Django 4.2.7 on 2024-02-24 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0012_remove_room_total_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hostel',
        ),
    ]
