# Generated by Django 4.2.7 on 2024-02-25 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0013_remove_room_hostel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='current_capacity',
            new_name='current_occupants',
        ),
    ]
