# Generated by Django 4.2.7 on 2024-02-25 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0014_rename_current_capacity_room_current_occupants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='is_registered',
            new_name='can_allot',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='current_occupants',
            new_name='current_capacity',
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('room_type', 'room_no')},
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_no', models.PositiveSmallIntegerField()),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='preference.hostel')),
            ],
            options={
                'unique_together': {('level_no', 'hostel')},
            },
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_allotted',
        ),
        migrations.AlterField(
            model_name='room',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='preference.level'),
        ),
    ]
