# Generated by Django 4.2.7 on 2024-02-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0015_rename_is_registered_room_can_allot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='layout_image',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
