# Generated by Django 4.2.7 on 2024-03-08 06:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0016_level_layout_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=2000), blank=True, default=list, size=None),
        ),
    ]
