# Generated by Django 4.2.7 on 2024-03-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0017_hostel_description_hostel_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='photo',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
