# Generated by Django 4.2.7 on 2024-05-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0018_roomtype_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='caretaker_phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostel',
            name='warden_email',
            field=models.EmailField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostel',
            name='warden_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostel',
            name='warden_phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
