# Generated by Django 4.2.7 on 2024-05-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0019_hostel_caretaker_phone_number_hostel_warden_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='caretaker_email',
            new_name='day_caretaker_email',
        ),
        migrations.RenameField(
            model_name='hostel',
            old_name='caretaker_name',
            new_name='day_caretaker_name',
        ),
        migrations.RenameField(
            model_name='hostel',
            old_name='caretaker_phone_number',
            new_name='day_caretaker_phone_number',
        ),
        migrations.AddField(
            model_name='hostel',
            name='night_caretaker_email',
            field=models.EmailField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostel',
            name='night_caretaker_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostel',
            name='night_caretaker_phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostel',
            name='warden_photo',
            field=models.URLField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
