# Generated by Django 4.2.7 on 2024-05-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0020_rename_caretaker_email_hostel_day_caretaker_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='day_caretaker_email',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='day_caretaker_phone_number',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='night_caretaker_email',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='night_caretaker_phone_number',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='warden_phone_number',
        ),
        migrations.AddField(
            model_name='hostel',
            name='caretaker_email',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='hostel',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='day_caretaker_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='night_caretaker_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='warden_email',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='warden_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='warden_photo',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
