# Generated by Django 4.2.7 on 2023-11-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_invitation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_preference_filling_live',
            field=models.BooleanField(default=False),
        ),
    ]
