# Generated by Django 4.2.7 on 2023-11-14 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0004_hostel_caretaker_email_hostel_caretaker_name_and_more'),
        ('student', '0003_batch_is_preference_filling_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_retain_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='current_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preference.roomtype'),
        ),
    ]
