# Generated by Django 4.2.7 on 2023-11-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_batch_is_retain_allowed_student_current_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='retain',
            field=models.BooleanField(default=False),
        ),
    ]
