# Generated by Django 4.2.7 on 2023-11-15 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_batch_is_preference_filling_live_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='student.batch'),
        ),
    ]
