# Generated by Django 4.2.7 on 2023-11-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_section_batch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('batch', 'gender')},
        ),
    ]
