# Generated by Django 4.2.7 on 2023-11-15 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0008_remove_roomtype_is_allotment_enabled_and_more'),
        ('student', '0007_alter_section_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.AddField(
            model_name='student',
            name='current_hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preference.hostel'),
        ),
    ]
