# Generated by Django 4.2.7 on 2023-11-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_student_branch_student_current_hostel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_hostel',
        ),
    ]
