# Generated by Django 4.2.7 on 2023-11-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_section_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='is_retain_allowed',
        ),
        migrations.AddField(
            model_name='section',
            name='is_retain_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
