# Generated by Django 4.2.7 on 2023-11-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_remove_batch_is_retain_allowed_and_more'),
        ('student', '0009_remove_student_current_hostel'),
    ]

    operations = [
    ]
