# Generated by Django 4.2.7 on 2023-11-16 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0008_remove_roomtype_is_allotment_enabled_and_more'),
        ('student', '0010_merge_20231116_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='alloted_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alloted_students', to='preference.roomtype'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='preference.roomtype'),
        ),
    ]
