# Generated by Django 4.2.7 on 2023-11-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_alloted_room_alter_student_current_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='retain',
            new_name='is_retained',
        ),
        migrations.AddField(
            model_name='group',
            name='is_preferences_filled',
            field=models.BooleanField(default=False),
        ),
    ]
