# Generated by Django 4.2.7 on 2023-11-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_rename_retain_group_is_retained_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phoneno',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
