# Generated by Django 4.2.7 on 2023-11-23 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_student_phoneno'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('to', 'for_group')},
        ),
    ]
