# Generated by Django 4.2.7 on 2023-12-02 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0009_alter_hostel_name_alter_preference_unique_together_and_more'),
        ('student', '0015_defaulter'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_allotment_status_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='preview_room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preview_students', to='preference.roomtype'),
        ),
    ]
