# Generated by Django 4.2.7 on 2023-12-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_rename_is_allotment_status_public_section_is_allotment_result_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='group_size_limit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
