# Generated by Django 4.2.7 on 2024-02-25 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0015_rename_is_registered_room_can_allot_and_more'),
        ('student', '0018_section_group_size_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='alloted_room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alloted_students', to='preference.room'),
        ),
    ]
