# Generated by Django 4.2.7 on 2024-05-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_student_alloted_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_room_allotment_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
