# Generated by Django 4.2.7 on 2024-05-08 06:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_section_is_room_allotment_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
