# Generated by Django 4.2.7 on 2024-05-08 06:09

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("student", "Student")
    for row in MyModel.objects.all():
        row.token = uuid.uuid4()
        row.save(update_fields=["token"])

class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_student_token'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
