# Generated by Django 4.2.7 on 2024-05-08 06:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_populate_student_token_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, unique=True),
        ),
    ]
