# Generated by Django 4.2.7 on 2024-05-08 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_invitation_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set(),
        ),
    ]
