# Generated by Django 5.1 on 2024-09-13 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='room',
            name='block',
        ),
        migrations.AddField(
            model_name='level',
            name='block',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='hostel.block'),
        ),
    ]
