# Generated by Django 5.1 on 2024-09-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_remove_level_hostel_remove_room_block_level_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='image_url',
            field=models.URLField(default=None, max_length=5000, null=True),
        ),
    ]
