# Generated by Django 5.1 on 2024-09-14 23:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningrequest',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cleaningrequest',
            name='level_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cleaningrequest',
            name='preferred_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='cleaningrequest',
            name='room_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cleaningrequest',
            name='preferred_slots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
