# Generated by Django 4.2.7 on 2024-09-01 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
        ('cleaning_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningrequest',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worker.worker'),
        ),
    ]
