# Generated by Django 5.1 on 2024-09-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_request', '0002_cleaningrequest_date_cleaningrequest_level_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='photo',
        ),
    ]
