# Generated by Django 5.1 on 2024-09-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_request', '0003_remove_feedback_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningrequest',
            name='level',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
