# Generated by Django 5.1 on 2024-09-29 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_request', '0004_cleaningrequest_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
