# Generated by Django 4.2.7 on 2023-11-11 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cg', models.FloatField()),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='login.student')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('groups', models.ManyToManyField(related_name='batch', to='allotment.group')),
                ('students', models.ManyToManyField(related_name='batch', to='login.student')),
            ],
        ),
    ]
