# Generated by Django 4.2.7 on 2023-12-02 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_defaulter'),
        ('preference', '0009_alter_hostel_name_alter_preference_unique_together_and_more'),
        ('dashboard', '0003_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllotmentLogsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cg', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='allotmentstatus',
            name='done',
        ),
        migrations.RemoveField(
            model_name='allotmentstatus',
            name='is_public',
        ),
        migrations.AddField(
            model_name='allotmentstatus',
            name='alloted_groups_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allotmentstatus',
            name='alloted_students_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allotmentstatus',
            name='partial_allot_groups_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allotmentstatus',
            name='partial_allot_students_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allotmentstatus',
            name='retained_groups_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allotmentstatus',
            name='retained_students_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allotmentstatus',
            name='sections',
            field=models.ManyToManyField(related_name='allotment_statuses', to='student.section'),
        ),
        migrations.CreateModel(
            name='AllotmentLogsStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('phoneno', models.CharField(max_length=15)),
                ('rollno', models.CharField(max_length=15)),
                ('cg', models.FloatField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='dashboard.allotmentlogsgroup')),
                ('preview_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preference.roomtype')),
            ],
        ),
        migrations.AddField(
            model_name='allotmentlogsgroup',
            name='leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader_of_group', to='dashboard.allotmentlogsstudent'),
        ),
        migrations.AddField(
            model_name='allotmentlogsgroup',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_groups', to='dashboard.allotmentstatus'),
        ),
    ]
