# Generated by Django 4.2.7 on 2023-12-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_allotmentlogsgroup_remove_allotmentstatus_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='fee_structure_url',
            field=models.URLField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
