# Generated by Django 4.2.7 on 2023-12-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_academicsession_fee_structure_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotmentlogsstudent',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
