# Generated by Django 4.2.7 on 2023-12-19 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_allotmentlogsstudent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotmentlogsstudent',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='dashboard.allotmentlogsgroup'),
        ),
    ]
