# Generated by Django 4.2.7 on 2023-12-19 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0009_alter_hostel_name_alter_preference_unique_together_and_more'),
        ('dashboard', '0007_alter_allotmentlogsstudent_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotmentlogsstudent',
            name='preview_room',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='preference.roomtype'),
        ),
    ]
