import type { InputRoomProps, SelectedRoomProps } from "@/hooks/mutation/use-room";

export const rooms1 = [
  {
      attached: 2,
      room: ['D-203', 'D-204'],
      availability: [0, 2],
      capacity: [4, 4],
      clusterId: 'cluster-1',
      ac:[true,false],
  },
  {
      attached: 2,
      room: ['D-205', 'D-206'],
      availability: [2, 1],
      capacity: [3, 3],
      clusterId: 'cluster-2',
      ac:[true,false],
  },
  {
      attached: 2,
      room: ['D-207', 'D-208'],
      availability: [2, 2],
      capacity: [2, 2],
      clusterId: 'cluster-3',
      ac:[true,false],
  },
  {
      attached: 2,
      room: ['D-209', 'D-210'],
      availability: [1, 1],
      capacity: [1, 1],
      clusterId: 'cluster-4',
      ac:[true,false],
  },
  {
      attached: 2,
      room: ['D-211', 'D-212'],
      availability: [3, 3],
      capacity: [4, 4],
      clusterId: 'cluster-5',
      ac:[true,false],
  },
  {
      attached: 2,
      room: ['D-213', 'D-214'],
      availability: [4, 2],
      capacity: [4, 4],
      clusterId: 'cluster-6',
      ac:[true,false],
  },
  {
      attached: 2,
      room: ['D-215', 'D-216'],
      availability: [3, 3],
      capacity: [4, 4],
      clusterId: 'cluster-7',
      ac:[true,false],
  },
  {
      attached: 2,
      room: ['D-217', 'D-218'],
      availability: [2, 4],
      capacity: [4, 4],
      clusterId: 'cluster-8',
      ac:[true,false],
  },
  {
      attached: 2,
      room: ['D-219', 'D-220'],
      availability: [4, 3],
      capacity: [4, 4],
      clusterId: 'cluster-9',
      ac:[true,false],
  },
  {
      attached: 2,
      room: ['D-221', 'D-222'],
      availability: [2, 4],
      capacity: [4, 4],
      clusterId: 'cluster-10',
      ac:[true,false],
  },
  {
      attached: 2,
      room: ['D-223', 'D-224'],
      availability: [3, 2],
      capacity: [4, 4],
      clusterId: 'cluster-11',
      ac:[true,false],
  },
  {
      attached: 2,
      room: ['D-225', 'D-226'],
      availability: [4, 3],
      capacity: [4, 4],
      clusterId: 'cluster-12',
      ac:[true,false],
  },
  {
      attached: 2,
      room: ['D-227', 'D-228'],
      availability: [4, 2],
      capacity: [4, 4],
      clusterId: 'cluster-13',
      ac:[true,false],
  },
  {
      attached: 2,
      room: ['D-229', 'D-230'],
      availability: [3, 4],
      capacity: [4, 4],
      clusterId: 'cluster-14',
      ac:[true,false],
  },
  {
      attached: 2,
      room: ['D-231', 'D-232'],
      availability: [4, 3],
      capacity: [4, 4],
      clusterId: 'cluster-15',
      ac:[true,false],
  },
  {
      attached: 2,
      room: ['D-233', 'D-234'],
      availability: [2, 2],
      capacity: [4, 4],
      clusterId: 'cluster-16',
      ac:[true,false],
  },
  {
      attached: 2,
      room: ['D-235', 'D-236'],
      availability: [4, 4],
      capacity: [4, 4],
      clusterId: 'cluster-17',
      ac:[true,false],
  },
  {
      attached: 2,
      room: ['D-237', 'D-238'],
      availability: [3, 2],
      capacity: [4, 4],
      clusterId: 'cluster-18',
      ac:[true,false],
  },
  {
      attached: 2,
      room: ['D-239', 'D-240'],
      availability: [2, 3],
      capacity: [4, 4],
      clusterId: 'cluster-19',
      ac:[true,false],
  },
  {
      attached: 2,
      room: ['D-241', 'D-242'],
      availability: [4, 4],
      capacity: [4, 4],
      clusterId: 'cluster-20',
      ac:[true,false],
  },
] as InputRoomProps[];



  export const selectedRooms1=[
    {
      attached: 'D-204',
      room: 'D-122',
      capacity: 4,
      floor: '2',
    },
    {
      attached: 'D-206',
      room: 'D-205',
      capacity: 1,
      floor: '2',
    },
    {
      attached: 'D-506',
      room: 'D-505',
      capacity: 3,
      floor: 'WST-4',
    },
    {
      attached: 'D-204',
      room: 'D-204',
      capacity: 4,
      floor: '2',
    },
    {
      attached: 'D-206',
      room: 'D-206',
      capacity: 1,
      floor: '2',
    },
    {
      attached: 'D-506',
      room: 'D-510',
      capacity: 3,
      floor: 'WST-4',
    },
    
  ] as SelectedRoomProps[];