version: '3'

services:
  hosmas-api:
    image: hosmas-api
    container_name: hosmas-api
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - hosmas-celery
    volumes:
      - ./static/:/app/static/
      - ./logs/:/app/logs/
      - ./media/:/app/media/
      - ./imported-data/:/app/imported-data/
    network_mode: "host"
  
  hosmas-celery:
    image: hosmas-celery
    container_name: hosmas-celery
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./logs/:/app/logs/
      - ./media/:/app/media/
      - ./imported-data/:/app/imported-data/
    command: celery -A config worker -l info --pool=gevent --concurrency=1 -n worker@%h --without-mingle --without-gossip --without-heartbeat
    network_mode: "host"
