version: '3'

services:
  hosmas-api:
    image: ccs/hosmas-api
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - hosmas-celery-default
      - hosmas-celery-priority
      - hosmas-celery-admin-task
    volumes:
      - ./static/:/app/static/
      - ./logs/:/app/logs/
      - ./media/:/app/media/
      - ./imported-data/:/app/imported-data/
    network_mode: "host"
  
  hosmas-celery-default:
    image: ccs/hosmas-celery-default
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery -A config worker -l info --pool=gevent --concurrency=3 -n worker@%h --without-mingle --without-gossip --without-heartbeat
    network_mode: "host"
