version: '3'

services:
  hosmasapi:
    image: ccs/hosmas
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./static/:/app/static/
      - ./logs/:/app/logs/
      - ./media/:/app/media/
    network_mode: "host"
