# Generated by Django 5.1 on 2024-09-02 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('password_reset_slug', models.CharField(blank=True, default=None, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hostel.hostel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='user.user')),
            ],
            options={
                'db_table': 'supervisor',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('roll_number', models.CharField(max_length=15, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('branch', models.CharField(max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hostel.room')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='user.user')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
