# Generated by Django 5.1 on 2024-09-15 11:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_attendance_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, size=None),
        ),
    ]
