from django.urls import path
from . import views

urlpatterns = [
      path('import-students/', views.ImportStudentsView.as_view(), name='import_students'),
      path('import-defaulters/', views.ImportDefaultersView.as_view(), name='import_defaulters'),
      path('getStudents/', views.getStudents.as_view()),
      path('getGroups/', views.getGroups.as_view()),
      path('getGroup/', views.getGroup.as_view()),
      path('getDefaulters/', views.getDefaulters.as_view()),
      path('profile/', views.ProfileView.as_view()),
      path('export/groups/', views.ExportGroupsView.as_view()),
      path('export/students/', views.ExportStudentsView.as_view()),
      path('allocate/', views.AllotmentView.as_view()),
      path('section/update/all-status/', views.UpdateSectionsAllotmentStatusView.as_view(), name='update_sections_allotment_status'),
      path('group/create/', views.CreateGroupView.as_view()),
      path('getFAQ/', views.getFAQ.as_view()),
      path('createFAQ/', views.createFAQ.as_view()),
      path('deleteFAQ/', views.deleteFAQ.as_view()),
      path('updateFAQ/', views.updateFAQ.as_view()),
      path('sendReminderMail/', views.sendReminderMail.as_view()),
      path('group/edit/add-member/', views.AddToGroupView.as_view()),
      path('group/edit/change-leader/', views.ChangeGroupLeaderView.as_view()),
      path('group/edit/remove-member/', views.RemoveFromGroupView.as_view()),
      path('groups/delete/', views.DeleteGroupsView.as_view()),
      path('<slug:model>/create/', views.CreateObjectView.as_view(), name='create_object'),
      path('<slug:model>/view/multiple/', views.GetMultipleObjectsView.as_view(), name='view_multiple_objects'),
      path('<slug:model>/view/<int:id>/', views.GetObjectView.as_view(), name='view_object'),
      path('<slug:model>/update/<int:id>/', views.UpdateObjectView.as_view(), name='update_object'),
      path('<slug:model>/delete/', views.DeleteObjectView.as_view(), name='delete_object'),
      path('<slug:model>/delete/multiple/', views.DeleteObjectsView.as_view(), name='delete_object'),
]