# Generated by Django 4.2.7 on 2024-09-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_id', models.IntegerField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('hostel_id', 'start', 'end')},
            },
        ),
    ]
