name: Mirror Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name "mirror-bot"
          git config --global user.email "mirror-bot@github.com"

      - name: Push Mirror
        run: |
          git push \
          https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/akaushesh/HOSMAS_FRONTEND.git \
          HEAD:main \
          --force
